name: satstress
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - astropy
  - astroquery
  - numpy
  - scipy
  - matplotlib
  - wxpython
  - basemap
  - gdal
  - pygraphviz
  - netcdf4
  - gfortran
  - pip